# Form implementation generated from reading ui file 'ui\anime_column.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AnimeColumn(object):
    def setupUi(self, AnimeColumn):
        AnimeColumn.setObjectName("AnimeColumn")
        AnimeColumn.resize(268, 443)
        self.horizontalLayout = QtWidgets.QHBoxLayout(AnimeColumn)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.animeCol = QtWidgets.QFrame(parent=AnimeColumn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.animeCol.sizePolicy().hasHeightForWidth())
        self.animeCol.setSizePolicy(sizePolicy)
        self.animeCol.setObjectName("animeCol")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.animeCol)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.animeView = QtWidgets.QLabel(parent=self.animeCol)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.animeView.sizePolicy().hasHeightForWidth())
        self.animeView.setSizePolicy(sizePolicy)
        self.animeView.setMinimumSize(QtCore.QSize(250, 350))
        self.animeView.setMaximumSize(QtCore.QSize(250, 350))
        self.animeView.setText("")
        self.animeView.setScaledContents(True)
        self.animeView.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignTop)
        self.animeView.setObjectName("animeView")
        self.verticalLayout_7.addWidget(self.animeView)
        self.animeTitle = QtWidgets.QLabel(parent=self.animeCol)
        self.animeTitle.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Soliden Trial Light Cond")
        font.setPointSize(13)
        self.animeTitle.setFont(font)
        self.animeTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.animeTitle.setWordWrap(True)
        self.animeTitle.setObjectName("animeTitle")
        self.verticalLayout_7.addWidget(self.animeTitle)
        self.animeInfo = QtWidgets.QLabel(parent=self.animeCol)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.animeInfo.setFont(font)
        self.animeInfo.setScaledContents(False)
        self.animeInfo.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.animeInfo.setObjectName("animeInfo")
        self.verticalLayout_7.addWidget(self.animeInfo)
        self.horizontalLayout.addWidget(self.animeCol)

        self.retranslateUi(AnimeColumn)
        QtCore.QMetaObject.connectSlotsByName(AnimeColumn)

    def retranslateUi(self, AnimeColumn):
        _translate = QtCore.QCoreApplication.translate
        AnimeColumn.setWindowTitle(_translate("AnimeColumn", "Form"))
        self.animeTitle.setText(_translate("AnimeColumn", "TextLabel"))
        self.animeInfo.setText(_translate("AnimeColumn", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AnimeColumn = QtWidgets.QWidget()
    ui = Ui_AnimeColumn()
    ui.setupUi(AnimeColumn)
    AnimeColumn.show()
    sys.exit(app.exec())
